// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisplayCount() {
  return window['go']['main']['App']['DisplayCount']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartTranslation() {
  return window['go']['main']['App']['StartTranslation']();
}

export function StopTranslation() {
  return window['go']['main']['App']['StopTranslation']();
}
