// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DisplayCount():Promise<number>;

export function GetConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartTranslation():Promise<void>;

export function StopTranslation():Promise<void>;
